# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses:
      - 192.168.56.22/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
        - 8.8.8.8
        search: []
    enp0s8:
      dhcp4: true
  version: 2
